name: "Remove a brand"
description: "Remove an existing brand from Product Radar"
title: "Remove brand: "
labels: ["brands:remove"]
body:
  - type: input
    id: brand_name
    attributes:
      label: Brand name
      placeholder: e.g. Stüssy
    validations:
      required: true
